name: Ping Server

on:
  schedule:
    # Runs every 13 minutes between 06:00 and 18:00 UTC (08:00–20:00 CET/CEST)
    - cron: "*/13 6-18 * * *"

jobs:
  ping-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ping Server
        run: curl -X GET https://habit-tracker-api-lyl1.onrender.com
